### ISSUE TITLE
Versioning of bosh releases?

### ISSUE THREAD

**Issue by aegershman** [18F/cg-deploy-bosh#366]
Do you all mind sharing how you version your bosh releases?

I'm interested in leveraging some bosh releases you all have. I can supply my own blobs and perform `bosh create-release` and such. But I'm struggling with how these releases are versioned. I get the impression the version is tracked in a private bucket by virtue of incrementing the version number in each `release-x.tgz` that gets generated.

In your bosh release repos, it looks like there's one initial release using an incremental schema ([oauth2-proxy](https://github.com/18F/oauth2-proxy-boshrelease/tree/master/releases/oauth2-proxy), [uaa-customized-proxy](https://github.com/18F/uaa-customized-boshrelease/blob/master/releases/uaa-customized/uaa-customized-1.yml), [nessus-agent](https://github.com/18F/cg-nessus-agent-boshrelease/blob/master/releases/nessus-agent/nessus-agent-1.yml), etc.), but no published releases from there-- and looking through the [pipelines/tasks in this repo](https://github.com/18F/cg-deploy-bosh/blob/master/releases/releases.yml), I get the impression versioning is [done using an incrementing count](https://github.com/18F/cg-pipeline-tasks/blob/master/finalize-bosh-release.sh#L9-L10) based on the previous packaged version; e.g., "myrelease-1", "myrelease-2".

 Is that fairly accurate?

Thanks a lot 👍

**Comment by mxplusb** [comment]
@aegershman it's a bit nuanced right now, and we're looking to change it sometime in the not so distant future, but here's how it works now.

1. Commit from one of our bosh release sources, we'll say `nessus-agent`.
1. We have a pipeline which handles all of our bosh releases, found [here](releases/pipeline.yml.erb).
1. Each release runs [this task](https://github.com/18F/cg-pipeline-tasks/blob/master/finalize-bosh-release.sh).
    1. Bosh runs `bosh create-release`.
    1. Bosh takes the last known version, performs a minor version increment. We don't override the default behaviour, iirc.
1. The release gets uploaded to our internal S3 bucket.
1. A different pipeline deploys the release after the new release is published to S3.

Does that answer your question?

**Comment by aegershman** [comment]
It does, this makes sense. Thank you for confirming; so if our org wanted to leverage some of these releases, we'd need to keep our own versioning of it.

It's not a big problem since I imagine most of changes to these bosh-releases would be small enough that they don't _need_ to be semantically versioned or have a public 'shared' version, where the `.final_builds` get committed back to the git repo.

**Comment by mxplusb** [comment]
@aegershman I'd be interested in hearing your use case if you can share it.

**Comment by aegershman** [comment]
Yes, the use-case is that our team would like to leverage/contribute to certain 18F BOSH releases--[specifically the nessus-agent bosh release](https://github.com/18F/cg-nessus-agent-boshrelease/pull/29)--and stay as close to the OSS source as possible. If we have to build our own releases due to closed-source binaries, that's completely understandable. Apologies, does that answer your question? I can get into much deeper specifics if you'd like. Also available on OSS cloudfoundry Slack

**Comment by mxplusb** [comment]
@aegershman that actually makes a lot of sense. We build our own bosh releases primarily because it met our needs, all of the folks who know why we didn't contribute them back to the standard bosh.io releases are gone now.

If you are willing to create a Nessus Agent pipeline which builds the release and uploads it to bosh.io (prolly best to put the pipeline in the Nessus package repo, if you can), I don't see a reason not to go that path; the whole point of us being OSS is to help others. We've been running the Nessus package in production for many years, so it's very stable.

//cc @bengerman13 @hillaryj

**Comment by mxplusb** [comment]
Closing due to age.
